### ISSUE TITLE
[nsm] feature request: auto-create temp session

### ISSUE THREAD

**Issue by rhetr** [original-male/non#139]
I set the NSM_URL and start nsmd in my .profile so nsm-aware applications I launch can automatically connect to the session. Sometimes I start carla up before nsm because i just want to toy around with some ideas but then I can't save it or anything since an NSM session isn't already open. It would be great for nsm to detect such scenarios and create a temp session that can either be later saved into a new unique session or discarded.

**Comment by rhetr** [comment]
I resolved this by writing a script that generates a unique folder name and sends /nsm/server/new folder_name to NSM. This is contingent on NSM_URL being set as a global environment variable in .profile (and on NSM already running).

Since a new folder is created at basically every login, sessions that have been created but not actually ever used should be deleted, so I run a function that does that before creating a new session. A problem is that if by some mistake my script is called while NSM is attached to an empty session, that session will be deleted and NSM segfaults. This normally should not be an issue but it'd be nice if that did not ever happen.

I thought this could be avoided if I waited for a reply from NSM since the NSM API v1.2 states that all messages are responded to at the sender's address. But in this case my script isn't a registered NSM client (nor should it be). Is there a way for a non-registered application to issue commands to NSM and receive a reply?

**Comment by original-male** [comment]
I'm not sure I understand. Do you want the reply so that you can test if
Nsmd is already running or if a session is open or...?

**Comment by original-male** [comment]
Oh and FYI, nsmd creates a hidden lock file in the open session directory.
You could use that to have your script avoid deleting the open session.

**Comment by rhetr** [comment]
sorry, I deleted my previous comment. I wanted the reply to make sure nsm has closed and exited its session so I wouldn't accidentally delete the directory it is using. I figured out how to receive the reply, but if there's a lock file that I can check that's possibly better.

previous comment:

> I resolved this by writing a script that generates a unique folder name and sends 
> /nsm/server/new folder_name to NSM. This is contingent on NSM_URL being set as a global 
> environment variable in .profile (and on NSM already running).

> Since a new folder is created at basically every login, sessions that have been created but not
> actually ever used should be deleted, so I run a function that does that before creating a new 
> session. A problem is that if by some mistake my script is called while NSM is attached to an 
> empty session, that session will be deleted and NSM segfaults. This normally should not be an 
> issue but it'd be nice if that did not ever happen.

> I thought this could be avoided if I waited for a reply from NSM since the NSM API v1.2 states that 
> all messages are responded to at the sender's address. But in this case my script isn't a registered 
> NSM client (nor should it be). Is there a way for a non-registered application to issue commands to 
> NSM and receive a reply?
