### ISSUE TITLE
[non-mixer] Delay with OSC commands when running non-mixer-noui

### ISSUE THREAD

**Issue by stez-mind** [original-male/non#152]
Hello,
I'm using non-mixer in a headless setup on an ARM board (Udoo quad, based on Freescale i.MX6q).

If I run non-mixer with its GUI under a DE everything works very well, but when running the same patch headless with non-mixer-noui I have very long latencies (2-3 secs) when applying external OSC commands.  I'm running the last git version compiled with g++ 4.9 on a Debian Wheezy.

For testing I'm just controlling a parameter in a LADSPA plugin, sending the value from Python with pyliblo. It seems that the problem, although with lower delays, is present also on my x86_64 system running Arch.

**Comment by stez-mind** [comment]
At the moment I'm working around the issue running non-mixer with Xvfb, with good results and unnoticeable computational overhead.

**Comment by jreusch-barco** [comment]
hey hey
i have the same problem, looks like in nonui mode it takes a long time to get the FL:lock
after passing the part
Fl::lock();
in Mixer.C it is as fast as in gui mode.
investigating further...

**Comment by stez-mind** [comment]
Yes,
I also found out that was the issue.

I've actually disabled the locks in non-ui mode, guessing that no GUI also means no possible race condition there.. or so I hope. Seems quite stable after some months of testing.

By the way, using locks in this way between the GUI and audio thread is usually bad as there is a huge priority inversion when the GUI thread is holding the lock, see [this excellent reference](http://www.rossbencina.com/code/real-time-audio-programming-101-time-waits-for-nothing) from Ross Bencina.

 Lock-free message queues are a better solution, although they will require some deep reorganization of the code.

**Comment by jreusch-barco** [comment]
oha cool :)
would you actually mind sharing the code?
i now also disabled it and it works, but using tested code let's me sleep better ;)

**Comment by original-male** [comment]
I'm curious also. I have a fix for this from when the issue was first reported, but I have been unable to test it due to my system being a bit screwed up from an upgrade and not having had time to repair it.

There should be no use of Fl::lock() between audio and GUI threads... Between GUI and OSC threads is a different matter... In any case, my fix involved removing a delay in the main loop for noui mode, not removing any locks. That's as far as I could get without being able to test.

If someone wants to try it, it's on the mixer-noui-fix branch.

**Comment by jreusch-barco** [comment]
the changes in mixer-nonui-fix don't solve this issue for me, sorry.
even worse, now it seems to not work at all :(
seems the change from Fl:check() -> Fl:wait() doesn't behave as expected.

**Comment by jreusch-barco** [comment]
just using
Fl::wait(100000); //arbitrary value...
solves the issue for me.
