### ISSUE TITLE
non-timeline segfault setting track >1 channel

### ISSUE THREAD

**Issue by forestcreature** [original-male/non#154]
trying to set a track's channel count to > 1 in non-timeline segfaults every time for me. each dmesg entry says that the segfault is in libpthread-2.17

slackware 14.1, kernel 3.10.17, non 1.2.0
(i've read the advice regarding binutils-gold. i don't have that package: the binutils package supplies ld.gold, but ld is linked to ld.bfd so i don't think it's being used)

**Comment by original-male** [comment]
Are you using a package or have you built from the latest git version?

Either way, I can't reproduce the problem here, so I'm going to need a backtrace from you to have any hope of solving it.

Instructions for getting a backtrace are provided here: http://non.tuxfamily.org/wiki/BugReports

**Comment by forestcreature** [comment]
this happens with my build from git clone, but was also the case earlier in the day with a slackbuild based on source from 23092014

backtrace is here http://pastebin.ca/2961826

cheers!

**Comment by original-male** [comment]
You seem to be missing most of the symbols from that backtrace (which are what makes them interesting). Are you sure you built everything (non and ntk) with debugging enabled? And are you sure you ran GDB against the same executable that crashed? 

Also, the the beginning of the output, GDB should say something about SEGFAULT in blah blah blah. That's the most interesting part. Without it I can't tell which thread is the one that triggered the crash.

**Comment by forestcreature** [comment]
gah sorry, yes, i wasn't thinking, and built it with debugging enabled but stripped symbols afterwards. duh!

backtrace with symbol tables: http://pastebin.ca/2961979
