### ISSUE TITLE
No way to remove Tempo marker

### ISSUE THREAD

**Issue by schrotie** [original-male/non#155]
It's easy to add tempo markers - even accidentally - but no way to remove them save for undo, which may require you to undo steps you did after adding the tempo marker.

**Comment by original-male** [comment]
Not so. There's a universal delete operation. Shift click.

**Comment by schrotie** [comment]
Hm, doesn't appear to work. BTW, it's fantastic what you achieved. I use mixer and timeline on an Eee PC at 5.8s latency. Got problems with the Looper eating CPU, Non is just mindboggling. I use different mixer instances in different parts of the processing chain. Big great thanks for this amazing software.

**Comment by original-male** [comment]
I meant Ctrl+Right Click. Here's the relevant part of the manual:

http://non.tuxfamily.org/timeline/doc/MANUAL.html#n:1.1.10.1.3.

**Comment by schrotie** [comment]
:-) Thanks a lot. And I even read the manual ... sorry for bothering.
