### ISSUE TITLE
[non-timeline] [patch] Add larger track height

### ISSUE THREAD

**Issue by jrigg** [original-male/non#156]
As an old guy whose eyes aren't what they used to be, I sometimes find that even the Huge track height isn't enough. I noticed the code in Track.C already contains a larger track height value that isn't being used. Here's a simple patch that adds it to the track header menu.
```
--- non/timeline/src/Track.C	2015-03-29 17:14:43.521993673 +0100
+++ non-patched/timeline/src/Track.C	2015-04-03 17:04:00.947995770 +0100
@@ -574,7 +574,7 @@
 void
 Track::size ( int v )
 {
-    if ( v < 0 || v > 3 )
+    if ( v < 0 || v > 4 )
         return;
 
     _size = v;
@@ -840,6 +840,10 @@
     {
         size( 3 );
     }
+    else if ( ! strcmp( picked, "Size/Enormous" ) )
+    {
+        size( 4 );
+    }
     else if ( ! strcmp( picked, "/Remove" ) )
     {
         int r = fl_choice( "Are you certain you want to remove track \"%s\"?", "Cancel", NULL, "Remove", name() );
@@ -984,6 +988,7 @@
     _menu.add( "Size/Medium",          FL_ALT + '2', 0, 0, FL_MENU_RADIO | ( s == 1 ? FL_MENU_VALUE : 0 ) );
     _menu.add( "Size/Large",           FL_ALT + '3', 0, 0, FL_MENU_RADIO | ( s == 2 ? FL_MENU_VALUE : 0 ) );
     _menu.add( "Size/Huge",           FL_ALT + '4', 0, 0, FL_MENU_RADIO | ( s == 3 ? FL_MENU_VALUE : 0 ) );
+    _menu.add( "Size/Enormous",           FL_ALT + '5', 0, 0, FL_MENU_RADIO | ( s == 4 ? FL_MENU_VALUE : 0 ) );
     _menu.add( "Flags/Record",         FL_CTRL + 'r', 0, 0, FL_MENU_TOGGLE | ( armed() ? FL_MENU_VALUE : 0 ) );
     _menu.add( "Flags/Mute",            FL_CTRL + 'm', 0, 0, FL_MENU_TOGGLE | ( mute() ? FL_MENU_VALUE : 0 ) );
     _menu.add( "Flags/Solo",           FL_CTRL + 's', 0, 0, FL_MENU_TOGGLE | ( solo() ? FL_MENU_VALUE : 0 ) );
```

**Comment by original-male** [comment]
Out of curiosity, could you post a screenshot of what this looks like on
your screen? What size and resolution is your monitor? What kind of details
do you need this height to see?

**Comment by jrigg** [comment]
I use a variety of monitors from 17" 1280x1024 to 22" 1680x1050. The existing Huge track height is usually fine when recording mainly mono files. 

The problem typically occurs when mastering stereo files that were mixed by others. The waveform height is half the size compared to mono. Normalizing is not very usable when mastering a collection of files which need to have the correct rms levels relative to each other, as a few isolated loud peaks can skew the levels by unpredictable amounts which are time-consuming to correct. 

If there are any clicks and noises which need removing they can be hard to see. A larger track height in non-timeline would reduce the number of times I need to resort to external programs like mhwaveedit to deal with such things.

I can send you a screenshot of a typical mastering session by email (I won't post it here without the client's permission). In the meantime I've attached a screenshot of a simple test mastering session.

![ntscreenshot-sn](https://cloud.githubusercontent.com/assets/6928427/6994351/430839b0-db0e-11e4-8501-a25b98e5477a.jpg)
