### ISSUE TITLE
[non-timeline] Fade-outs become invisible when zoomed in

### ISSUE THREAD

**Issue by jrigg** [original-male/non#164]
Region fade-outs become invisible when zoomed in. The zoom level where this occurs varies depending on whether the fade-out is at a split and also on number of tracks (at a split it tends to happen at lower zoom levels with more tracks in the project), but there is always a level above which the fade-out disappears from the display. The fade-out is still present in the history file and is still audible. Fade-ins do not appear to be affected.

Not being able to see the fade-outs makes it very difficult to do detailed edits like attenuating clicks and pops.

**Comment by jrigg** [comment]
BTW I'm using the black Cairo theme, in which region overlaps are less visible than with the lighter themes. If the overlaps were more visible it would mitigate the problem of not being able to see the amount of overlap when the bright yellow fade-out disappears.

**Comment by jrigg** [comment]
I can confirm that the fade-outs now work at high zoom levels. However there is a new problem: when splitting a region (S or Shift+S) the split line shows up as a grey bar approx. 10 pixels wide to the left of the playhead. Sometimes a redraw is necessary to make the bar appear, but once there it stays in all but the lowest few zoom levels, It obscures the end of the preceding region (along with the part of the fade-out covered by the bar). On further zooming in the grey bar stays at around 10 pixels wide.

**Comment by jrigg** [comment]
The problem appears to be connected to the changes made in Sequence_Widget.C.
line 192:  ```_sequence->drawable_x() - 10 : ```
line 234:  ```return (int)min( rw, (long)(_sequence->drawable_w() + 20)  );```

Changing those to the following seems to fix it:
line 192: ```_sequence->drawable_x() - 1 : ```
line 234 ```return (int)min( rw, (long)(_sequence->drawable_w() + 2)  );```

**Comment by original-male** [comment]
@jrigg your change may fix that but cause an artifact when scrolling.

I've pushed another change. Can you confirm that the region box drawing is fixed?

**Comment by jrigg** [comment]
Confirmed. Thanks for fixing.
