### ISSUE TITLE
[non-timeline] DND import fails on lowest track(s) if more than 4 tracks present

### ISSUE THREAD

**Issue by jrigg** [original-male/non#165]
Drag-and-drop import to the lowest track(s) fails silently if more than 4 tracks are present. Can be worked around by moving lowest track (with Shift+1) up a few positions, importing and then moving the track back down (Shift+2).

**Comment by nico202** [comment]
It seems to be related to the relative position within the window. When it fails, enlarge the window size and it'll allow you

**Comment by nico202** [comment]
if it helps, Audio_Sequence::handle in this situation is not receiving FL_PASTE (only FL_DND_ENTER and FL_DND_DRAG, but no FL_PASTE on release)

**Comment by original-male** [comment]
@nico202 Thanks that helped.
