### ISSUE TITLE
[non-timeline+non-mixer] OSC signal interfering

### ISSUE THREAD

**Issue by nico202** [original-male/non#180]
Here a bugged NSM session. All sessions I create like this suffer the same problem. 

http://wikisend.com/download/361304/OSC_Interfering.tar.gz
(also, I'm on the latest git)
(The first time I play this session, both sliders end up syncing at -47.61. If I play it again, they go to -70)
(Also, same session with my workaround works)

**Comment by original-male** [comment]
@nico202 The example session was very helpful. Thanks.
