### ISSUE TITLE
[non-timeline/non-mixer] Another OSC related segfault

### ISSUE THREAD

**Issue by nico202** [original-male/non#184]
Hi male, thanks for your work and sorry if i'm reporting that much.
non-timeline is still crashing if I add a control, change it's name, link it to the mixer slider, remove it, add one other and connect to the same slider. Non-mixer is not removing the mapping beetween the two, and again it's due to: OSC::Endpoint::osc_sig_handler(char const*, char const*, lo_arg**, int, void*, void*) (). Deleting the "mappings" file make the session useble again.

I'll debug it better when I have some time, this is just a placeholder to let you know.
(However, everything is working way better now)

**Comment by original-male** [comment]
@nico202 the issue of the mapping persisting in Non-Mixer after the control sequence is removed in Non-Timeline is a separate problem and not a bug exactly, but a limitation of the current protocol. If the mapping were removed when the signal is, then closing and reopening non-timeline in a session while non-mixer is running would permanently wipe out all the signal connection between the two. If this behavior still bothers you, feel free to create another issue for it.
