### ISSUE TITLE
non-daw: Resource leak ?

### ISSUE THREAD

**Issue by dcb314** [original-male/non#187]

**Comment by dcb314** [comment]
[../session-manager/src/nsmd.C:1333]: (error) Resource leak: fp

$ fgrep -n fp ../BUILD/non-daw-20131026/session-manager/src/nsmd.C | egrep "fopen|fclose"
907:    FILE *fp = fopen( session_file, "w+" );
918:    fclose( fp );
1196:    if ( ! ( fp = fopen( session_file, "r" ) ) )
$ 

Looks like a missing call to fclose to me.

**Comment by original-male** [comment]
Did this present a problem for you? Where did that error message come from?

Or are you just auditing the code for fun?

**Comment by dcb314** [comment]
>Where did that error message come from?

cppcheck, a static analysis tool for C and C++.

>Or are you just auditing the code for fun?

This.

**Comment by original-male** [comment]
I see. In that case, keep 'em coming!

**Comment by dcb314** [comment]
[../session-manager/src/nsm-proxy.C:505]: (error) Memory leak: new_filename
[../session-manager/src/nsmd.C:919]: (error) Memory leak: session_file
[../session-manager/src/nsmd.C:1333]: (error) Memory leak: session_file
