### ISSUE TITLE
Non Mixer - Crash when try to set Auto Input the second time on a track

### ISSUE THREAD

**Issue by lolgab** [original-male/non#188]
I create a "Master" track on non-mixer. Then I set "Auto Input" to mains and it works well. Then, when I realize that the Master track is mono I change the channel number to 2. When I realize that now the sends from other tracks are on the first channel only I try to set Auto Input to main again, and Non-Mixer crashes.

Non-Mixer 1.2.0~git20160210-1kxstudio1 from the kxstudio repository on elementaryOS Freya (ubuntu 14.04)
Launched from Non-session-manager

**Comment by original-male** [comment]
FYI, you should no longer have the first problem either (increasing the channel number on the master track will now trigger the auto-connection).
