### ISSUE TITLE
[non-timeline] Playback sometimes glitches at start of region

### ISSUE THREAD

**Issue by jrigg** [original-male/non#204]
On playback of a recorded region there is sometimes a glitch at the beginning, causing an audible thump. This behaviour seems to occur when the complexity of a project gets above a certain level. It doesn't always happen, but once it starts it occurs often enough to be a problem. It still happens (on the same tracks) after shutting down and rebooting.

I'm working on a project now where it's preventing me from running a mix. I mixed (using non-mixer) some multitracked guitars onto a new stereo track, then split up the new track into three regions for editing. Playback produces intermittent glitching at one or more of the new region starts. Which one is affected varies at random.

I've attached Snd screenshots showing the start of a region and a recording of the same region when a glitch occurred. The glitch shows as a separate chunk of sound followed by a dip. After that the region sounds correct.

![gtrheavy](https://cloud.githubusercontent.com/assets/6928427/20689157/cfe0594c-b5bb-11e6-9948-d56868e1586a.jpg)

![gtrheavyrec](https://cloud.githubusercontent.com/assets/6928427/20686691/992baa8c-b5b1-11e6-9182-62b97f112261.jpg)

**Comment by original-male** [comment]
Questions:

1) What's your JACK buffer size?
2) Are the regions abutted or overlapping?
3) What is the fade in/out duration on the regions?
4) Have you tried increasing either the fade in duration of the regions or the JACK buffer size? Did it make any difference?

**Comment by jrigg** [comment]
1. JACK buffer size 1024 (recent jack2 git version).
2. The example in the screenshot has a crossfade with a duplicate of an earlier region some time later than the section shown.
3. Fade in and out are both default on this example. The crossfade is about 0.5s.
4. If I make the fade in quite long it seems to cure it but it's too long to use.

It's late here (UK) so I'll have to continue tomorrow. I'll gather more info over the next couple of days and report back.

**Comment by jrigg** [comment]
More info:
Switching playback latency compensation off had no noticeable effect on the glitching.
Reducing JACK period size to 512 did affect it. It played back cleanly and I couldn't get it to glitch.

I recorded a clean copy of the edited track to a new track with -p512, removed the original edited regions and restarted the session with -p1024. Without the edited regions which were glitching at -p1024 everything plays back correctly.

The original (glitching) file was about  2min 30sec long. It consisted of three sections of sound separated by two fairly long gaps of silence. I split it into three regions with sound and removed the two regions of silence in between. I then duplicated the first region and replaced the beginning of the third region with it, putting a 0.5s crossfade at the end of the replaced section.

This isn't the first time I've encountered the problem. A few weeks ago I was mixing another project which kept glitching at the very start. Because it only did it there I recorded a mix and edited out the thump afterwards in Snd (I didn't have time to look into it further at the time). I realise this report probably isn't very helpful as the problem is so intermittent that it's hard to find a consistent trigger.

**Comment by jrigg** [comment]
One more thing. The new track I recorded was started a bar before the sound began so there was a bar of silence at the start. Now that I've trimmed off the silence the glitch at the beginning is back. It happens about 50% of the time on repeated plays. It isn't audible when there's silence at the start, which makes me suspect that it's a gain fluctuation. None of the other tracks in the project are doing it, which was also the case in the earlier project I mentioned.

**Comment by jrigg** [comment]
In order to show things more clearly I recorded a short test file of a 10kHz -1dBFS sine wave. I then recorded a copy of that to a new track. The copy had glitches at the beginning **and at the end**. Snd screenshots below.

Start of original file:
![nt-glitch-test](https://cloud.githubusercontent.com/assets/6928427/20860658/1fd73b02-b975-11e6-8e85-85a837e0c02c.jpg)
Start of copy:
![nt-glitch-test2](https://cloud.githubusercontent.com/assets/6928427/20860662/2d7965f0-b975-11e6-8a11-8b27ba05151b.jpg)
End of original file:
![nt-glitch-testb](https://cloud.githubusercontent.com/assets/6928427/20860664/382a4410-b975-11e6-9dff-d5a2c7e4dd87.jpg)
End of copy:
![nt-glitch-test2b](https://cloud.githubusercontent.com/assets/6928427/20860668/43d1a402-b975-11e6-8167-bcc69a73c916.jpg)
Both ends of the copy file should show the default sigmoid fade. It looks almost like the beginning has a correct fade-in followed immediately by part of a sigmoid fade-out. The end looks like separate, incorrectly ordered chunks of a sigmoid fade-out with a sigmoid fade-in between them. Is this possible?

**Comment by original-male** [comment]
Thanks for the research. Yeah, it's possible. It looks like the logic for spreading the declick fade across multiple JACK buffers isn't working correctly (from your testing it looks like maybe it's overshooting its goal when the JACK buffer size is larger than the fade length).

**Comment by jrigg** [comment]
I think your assessment may be correct. At -p512, two out of three copies of the test file glitched. At -p256, five out of five copies had correct fade-ins and fade-outs.

**Comment by original-male** [comment]
Let me know if this fixes your project. The changes I pushed should fix regular fade in/out and declicking, but there are still some related issues with loop declicking.

**Comment by jrigg** [comment]
Fade in/out and declicks now work correctly. Thanks for fixing.

**Comment by original-male** [comment]
@jrigg FYI, I just pushed another change to fix the declicking for looped regions.

**Comment by jrigg** [comment]
Thanks. Can confirm looping works correctly here.
