### ISSUE TITLE
[non-timeline] ways to import audio (without drag and drop)

### ISSUE THREAD

**Issue by PaulBatchelor** [original-male/non#211]
I've looked through the timeline manual, and it seems that the only way to import audio is through "drag'n'drop". However, the issue for me is that I don't use a file manager, and I don't even have one installed on my computer. On the one hand, I can see the advantages towards having "one way" to do things. On the other hand, I'd rather not have to install an entire file manager (often bloated) just to be able to import audio.  

I'm wondering, what kind of difficulties are there in having some sort of "import audio" menu option? My thinking is that it could be either in the right click menu or the toolbar menu, where a file dialogue could pop up and I could select a file. 

Thanks!

**Comment by nico202** [comment]
If you are in a hurry and need to do it without a FM, you can do it manually by editing the history.
You just need a software like sox/ffmpeg/mediainfo to get the frame number.
My old example script: https://github.com/swh/timemachine/issues/2

**Comment by original-male** [comment]
If it were in the File menu, then you'd not only have to select a file but also a track (and location).

If it were in the per-track context menus, then you'd just have to select a file. But that still leaves the question of location... Would the clip be inserted at the playhead? Near where the mouse had clicked? What if you used the keyboard to bring up the context menu?

This primary difficulty of adding this feature lies in answering these questions.

**Comment by jerash** [comment]
Le 22 mars 2017 à 16:56, Jonathan Moore Liles <notifications@github.com> a écrit :

> If it were in the File menu, then you'd not only have to select a file but also a track (and location).
> 
> If it were in the per-track context menus, then you'd just have to select a file. But that still leaves the question of location... Would the clip be inserted at the playhead? Near where the mouse had clicked? What if you used the keyboard to bring up the context menu?
> 
> This primary difficulty of adding this feature lies in answering these questions.

one could select file/import, choose the file on a selection popup window, and then have the waveform stick to the mouse and continue as if it was a drag'n'drop 

Raphaël

**Comment by original-male** [comment]
That introduces a new set of problems. After a file has been selected, the mouse button is in the up position. Having the mouse button up with an object attached to the cursor violates the drag 'n drop metaphor (and implementation).

**Comment by PaulBatchelor** [comment]
There's no rush on my end, but this looks cool in it's own right. I'll
check it out...

**Comment by jrigg** [comment]
> If it were in the per-track context menus, then you'd just have to select a file. But that still leaves the question of location... 

I'd settle for locating it at the start, then dragging into position afterwards. It may be only a partial solution, but would be useful nevertheless.

I have xfe installed, which is relatively lightweight by DnD FM standards, but I only use it for importing files to non-timeline.

**Comment by PaulBatchelor** [comment]
1. What if the "import audio file" feature was *only* available as a right click menu:
- right click on where you want to import the audio track
- select "import audio.." 
- file dialog pops up, you select the audio file
- Non inserts it where you initially spawned the right-click menu 

2. There could be some merit to implementing a clip list. Here is how it looks in Pro Tools

![cliplist](https://cloud.githubusercontent.com/assets/8139389/24307392/38f33196-1081-11e7-9329-f13b01e78faa.png)

You could CND from the file list, and use the the file dialogue to unambiguously import audio files to the list. This would be nice for my needs, which revolve around more sampled loop-based music rather than recorded music.

3. What would the difficulty be in reloading project files without completely restarting timeline? One could write programs to programatically generate or modify projects underneath, then non could reread the files.

**Comment by original-male** [comment]
1. Sounds reasonable to me.
2. Personally, I don't see the value in these clip lists. Perhaps someone could enlighten me.
3. This is insane. The project format is a journal and should only ever be appended to, not rewritten. However, this does mean that theoretically it would be simple for NT to accept journal entries added by external programs at runtime, without 'reloading' any of the previous entries (something which would be quite a different story for programs with typical XML based project formats.) I'm not convinced that that would be a good way to accomplish anything though.

**Comment by PaulBatchelor** [comment]
> Sounds reasonable to me.

This feature would be enough for me.

> Personally, I don't see the value in these clip lists. Perhaps someone could enlighten me.

These come in handy for things that use a lot of pre-recorded samples. Loop based music and music concrete come to mind. As I write this though, the Unixy part of me is realizing that a simple file manager could probably do a much better job than anything written internally. I could also see this concept leading to feature creep. Slowly catching on here...

> This is insane. 

ha. Pardon my ignorance, and thanks for the explanation.

**Comment by original-male** [comment]
I thought about writing a sample browser with previews, but I don't have much need for one myself and there seem to be several extant projects which do the same thing, such as samplecat (https://github.com/ayyi/samplecat) and, of course, most file managers.

**Comment by jrigg** [comment]
> Timeline: Add option to import source at mouse via timeline context m…
	
Thanks for adding this. Very useful.
