### ISSUE TITLE
[non-mixer] LV2 support for the Plug-in module?

### ISSUE THREAD

**Issue by unfa** [original-male/non#215]
I wonder if there are any plans on implementing LV2 plugin support for Non Mixer, or should I use external plugin hosts like Carla?

**Comment by falkTX** [comment]
See #146.

**Comment by jrigg** [comment]
With LV2 hosts like Carla, jalv and ingen available, is there really a need for LV2 support in non-mixer?

LV2 still appears to be a work-in-progress, with frequent changes which break things, which would add to the maintenance burden. In addition, introducing dependencies on other graphics toolkits would be a retrograde step IMO. I know LV2 GUIs haven't been discussed yet, but I think it would only be a matter of time. It would undermine Non's simplicity, which is one of its major strengths.

As an aside, I can only think of one or two LV2 plugins which do something no exisiting LADSPA plugin can, and for which no standalone JACK client equivalent is available. (It would be nice if more of those standalone JACK clients supported NSM, but that's a separate issue).

**Comment by unfa** [comment]
I see. It's true, that external hosts make a lot of sense, especially with the JACK-based and modular nature of Non.
