### ISSUE TITLE
[ntk] New release?

### ISSUE THREAD

**Issue by simonvanderveldt** [original-male/non#221]
Would it be possible to create a new release for ntk? The last tag (https://git.tuxfamily.org/non/fltk.git/tag/?h=v1.3.0) is from 2013.

Some small changes were done this year, the last commit being from april (https://git.tuxfamily.org/non/fltk.git/commit/?id=92365eca0f9a6f054abc70489c009aba0fcde0ff).
Maybe that commit can be tagged as a new release?

**Comment by original-male** [comment]
Do you have any suggestions for a version number? It's kind of a tricky situation (1.3.0 is the version of FLTK at the time of the fork...)

**Comment by simonvanderveldt** [comment]
> Do you have any suggestions for a version number? It's kind of a tricky situation (1.3.0 is the version of FLTK at the time of the fork...)

Hmm, good question.
Do you see ntk as a distinct product from fltk or as a "v2"?

**Comment by original-male** [comment]
Well, there's already an FLTK 2.0 (which is effectively a completely different product). FLTK's versioning has a pretty complicated history (see http://www.fltk.org/articles.php?L825). 

NTK is not ABI compatible with any version of FLTK (C++ is pretty hopeless when it comes to maintaining ABI compatibility anyway), but it is mostly source code compatible with 1.3.0 (that is, simple applications can be compiled without changes... more complex applications will likely require some changes to deal with the implications of alpha-channels on overlapping widgets).

I know from conversations with the FLTK developers that they have no intention of accepting any of the changes NTK introduces (although Bill Spitzak, the inventor of FLTK, seemed to agree with my decision to use Cario to draw everything). There's a lot of legacy inertia there...

Anyway, I think calling NTK version 2 or 3 is no less confusing. I did consider starting at 10 or -1 or something... Although NTK is still mostly source compatible with FLTK 1.3.0, that's not really mandate. 

I feel like any version I number I choose is going to be confusing.

**Comment by simonvanderveldt** [comment]
@original-male Sounds like NTK should be treated as something totally separate, that narrows it down (slightly :P) to not being 1.3.0+.

> I feel like any version I number I choose is going to be confusing.

Well, in that case I'd say just pick one. 0.x.x or 1.x.x maybe?

**Comment by original-male** [comment]
New version is v1.3.1000.
