### ISSUE TITLE
[non-timeline] No sound

### ISSUE THREAD

**Issue by marttt** [original-male/non#222]
Hi. I'm on Tiny Core Linux 7.4. Non-timeline 1.2.0 is built from latest source. Waveform playback starts, but with no sound.

For realtime scheduling to work on this distro, I'm using `set_rlimits` [1]. Here's the log:

    tc@box:/mnt/sda1/tce/optional$ set_rlimits non-timeline
    The Non-Timeline 1.2.0 -- Copyright (C) 2008-2013 Jonathan Moore Liles
    [non-timeline] Starting GUI
    OSC=osc.udp://box:16568/
    X_ChangeProperty: BadValue (integer parameter out of range for operation) 0x0
    Cannot connect to server socket err = No such file or directory
    Cannot connect to server socket
    jackdmp 1.9.7
    Copyright 2001-2005 Paul Davis and others.
    Copyright 2004-2011 Grame.
    jackdmp comes with ABSOLUTELY NO WARRANTY
    This is free software, and you are welcome to redistribute it
    under certain conditions; see the file COPYING for details
    no message buffer overruns
    no message buffer overruns
    JACK server starting in realtime mode with priority 10
    creating alsa driver ... hw:0|hw:0|1024|2|48000|0|0|nomon|swmeter|-|16bit
    control device hw:0
    configuring for 48000Hz, period = 1024 frames (21.3 ms), buffer = 2 periods
    ALSA: final selected sample format for capture: 16bit little-endian
    ALSA: use 2 periods for capture
    ALSA: final selected sample format for playback: 16bit little-endian
    ALSA: use 2 periods for playback
    [non-timeline] Info: created by = Non-Timeline 1.2.0
    [non-timeline] Info: created on = Sat Oct 21 09:13:25 2017
    [non-timeline] Info: version = 2
    [non-timeline] Info: sample rate = 48000
    [non-timeline] Replaying journal
    [0.146000ms] Replayed journal
    [non-timeline] Loaded project "/home/tc/proov2/"
    [non-timeline] Programming error: attempt to add sequence widget to the same sequence twice
    [non-timeline] Programming error: attempt to add sequence widget to the same sequence twice
    [non-timeline] Created project "/home/tc//proov2" from template "(null)"
    pasted file "//home/tc/aju/oy/oetjen/piano2.wav"
    [0.348000ms] Opened audio file
    [non-timeline] Failed to open peakfile for reading: No such file or directory

`.jackdrc` is as follows. (The `-S` forces 16bit mode; I'm trying this since the default 32bit didn't work. The files I'm working/testing with are of type signed 16 bit Little Endian, rate 48000 Hz, stereo.)

    /usr/local/bin/jackd -d alsa -d hw:0 -r 48000 -S

And `.asoundrc` (for default playback through Zoom H1):

    pcm.!default { 
     type plug 
     slave { 
     pcm "hw:2,0" 
     } 
    } 

Playback works with these settings without issues in aplay, sox, ecasound and Audacity. So the ALSA config seem to be fine. As for JACK, I'm not so sure.

Any help appreciated. Many thanks!

[1] https://wiki.linuxaudio.org/apps/all/set_rlimits

**Comment by jrigg** [comment]
[non-timeline] Failed to open peakfile for reading: No such file or directory

What is in the project sources directory? You should have the audio file (or valid symlink to it) plus an associated peakfile. The peakfile will have the same name as the audio file with '.peak' added to the end, eg. peakfile for 'somefile.wav' would be 'somefile.wav.peak' .

Things might be clearer if you start jackd before non-timeline so the messages don't get mixed up. What console messages do you get from 'set_rlimits jackd -d alsa -d hw:0 -r 48000 -S' ?

**Comment by marttt** [comment]
Thanks! The missing peakfile error disappeared after I re-opened the session.

As for jackd: I tried the command you mention with `hw:0` (which is
how .asoundrc should map my external playback device), `hw:2` (which
is how aplay -l maps it), `plughw:2` and `plughw:0` (alternatives to
the former). All three produce no sound in non-timeline and console
output with no significant differences.

Here's output for jackd and hw:0:

    tc@box:~/proov/sources$ set_rlimits /usr/local/bin/jackd -d alsa
-d hw:0 -r 4800
    0 -S
    jackdmp 1.9.7
    Copyright 2001-2005 Paul Davis and others.
    Copyright 2004-2011 Grame.
    jackdmp comes with ABSOLUTELY NO WARRANTY
    This is free software, and you are welcome to redistribute it
    under certain conditions; see the file COPYING for details
    no message buffer overruns
    no message buffer overruns
    JACK server starting in realtime mode with priority 10
    creating alsa driver ... hw:0|hw:0|1024|2|48000|0|0|nomon|swmeter|-|16bit
    control device hw:0
    configuring for 48000Hz, period = 1024 frames (21.3 ms), buffer = 2 periods
    ALSA: final selected sample format for capture: 16bit little-endian
    ALSA: use 2 periods for capture
    ALSA: final selected sample format for playback: 16bit little-endian
    ALSA: use 2 periods for playback

And here's the corresponding output for non-timeline (launched
separately, right after jackd):

    tc@box:~$ set_rlimits non-timeline
    The Non-Timeline 1.2.0 -- Copyright (C) 2008-2013 Jonathan Moore Liles
    [non-timeline] Starting GUI
    OSC=osc.udp://box:18377/
    X_ChangeProperty: BadValue (integer parameter out of range for
operation) 0x0
    [non-timeline] Info: created by = Non-Timeline 1.2.0
    [non-timeline] Info: created on = Wed Oct 25 21:57:12 2017
    [non-timeline] Info: version = 2
    [non-timeline] Info: sample rate = 48000
    [non-timeline] Loading snapshot
    [non-timeline] xrun
    [non-timeline] xrun
    [non-timeline] xrun
    [0.352000ms] Opened audio file
    [non-timeline] xrun
    [364.278000ms] Replayed journal
    [non-timeline] Loaded project "/home/tc/proov/"
    [non-timeline] xrun
    [non-timeline] xrun
    [364.278000ms] Replayed journal
    [non-timeline] Loaded project "/home/tc/proov/"
    [non-timeline] xrun
    [non-timeline] xrun
    [non-timeline] xrun

What is this `X_ChangeProperty ...` about?

I think jack isn't communicating with alsa. (I was also wrong
previously: ecasound doesn't want to play the file back through jack,
just alsa.) Maybe this will help, I'll look into it:
https://www.alsa-project.org/main/index.php/Asoundrc#JACK_plugin

Thanks again.

**Comment by jrigg** [comment]
I'm not sure the X_ChangeProperty message is important here.

I suspect a problem with jackd finding the right interface. You can check how your audio interfaces are mapped by looking at the /proc/asound/cards file.

What happens if you get rid of .asoundrc? You shouldn't need .asoundrc unless you have a specific reason for using it.

Also check whether a simple jack playback program like jack-play can play the file.

**Comment by marttt** [comment]
thanks jrigg,
my preferred device is mapped like this in /proc/asound/cards:

2 [H1	]: USB-Audio - H1
	Zoom Corporation H1 at usb-0000:00:1d.1-1, full speed

So I guess 'hw:2,0' should to be the correct alsa device. Somehow jack
doesn't recognize it.
Unfortunately this tiny Linux distro doesn't have jack-play available,
and I also failed building it. But jack devices aren't visible in e.g.
Audacity either. So I think it's an obvious issue with the system not
recognizing jack.

jackd seems to start fine, both from the command line and using qjackctl.

I might try this with a debian-based distro on the same machine.

**Comment by jrigg** [comment]
I would guess 'hw:2', but you said you tried that without success. If jackd runs there must be some valid jack ports. If you add the -v option to the jackd command line it will list the ports it can see. Alternatively use jack_lsp after starting jackd to list available ports.

If that doesn't give enough clues to what is happening you might have better luck asking on the alsa-user or linux-audio-user mailing lists.

**Comment by marttt** [comment]
'jack_lsp' output (both with and without sudo)

    tc@box:~$ sudo jack_lsp
    system:capture_1
    system:capture_2
    system:playback_1
    system:playback_2

I was (unsuccessfully) trying jack-alsa routing as taught here:
http://www.jackaudio.org/faq/routing_alsa.html

So this corresponds to what I have in ~/.asoundrc now
(in addition to setting 'hw:2,0' as the default device for alsa.
But, curiously, with .asoundrc disabled, the output is the same.

Should I somehow change these ports to 'hw:2,0'?

**Comment by jrigg** [comment]
jackd can see the in/out ports so there shouldn't be a problem. You don't need to manually route alsa to jack ports as the jackd alsa driver does it for you. You do however need to manually route the non-timeline track outputs to the system:playback ports using either the jack_connect command or a JACK connection manager. On a minimal system I'd recommend njconnect [https://sourceforge.net/projects/njconnect/](url)

**Comment by marttt** [comment]
Ugh. Many thanks, it works flawlessly now! :)
I've little experience with jack routing, so somehow I couldn't get
qjackctl to display the non-timeline ports. :/
This is really embarrassing, I apologize for wasting your time with my logs etc.

Also, thanks for pointing me to njconnect. A minimalist tool like this
is just what I needed (qjackctl is a bit too much for my needs).

Thanks again!

**Comment by jrigg** [comment]
Glad you got it working. You might want to close the issue :-)
