### ISSUE TITLE
release for packaging

### ISSUE THREAD

**Issue by dvzrv** [original-male/non#224]
Hi!

I'm aware of #205, but I'd like to ask again for a new and preferably ongoing release cycle.
I recently took over a bunch of pro-audio packages for [community] in Arch Linux and I'd like to move some more pro-audio software from the Arch User Repository (AUR) to the main repository.
Arch may be rolling release, but this doesn't mean it will ship HEAD versions of software in its repositories.
Therefore, it would be awesome, if you could tag the non-software again, as I don't want to offer a version, that is more than five years old (as that is the latest stable).
Thanks!

**Comment by original-male** [comment]
OK. fetch and you shall receive.

I was holding off on this (but not really for any good reason) until I evaluated upgrading to the latest WAF and fixing some version-related issues. But three's really no reason not to go ahead and tag it here.

**Comment by dvzrv** [comment]
Thanks! You rule :)
