### ISSUE TITLE
[non-mixer] Segmentation fault (core dumped) when trying OSC learning 

### ISSUE THREAD

**Issue by layk** [original-male/non#227]
Hi
I get segmentation fault when trying to map OSC from TouchOSC or QuickOSC.
Way to reproduce:
1. Start non-mixer --osc-port 4444
2. Mixer ->Add Strip
3. Remote Control -> Start learning.
4. Click Mute button.
5. Push toggle button on Android client.
6. After one or two seconds i get segmentation fault(core dumped).

System Fedora core 27 x86_64
uname -a
Linux localhost.localdomain 4.14.12-300.rt10.1.fc27.ccrma.x86_64+rt
gcc --version
gcc (GCC) 7.3.1 20180130 (Red Hat 7.3.1-2)

I tried version that comes with distribution and compiled myself both with same result.

I noticed when doing waf configure in lib/ntk i got Checking for header sys/stdtypes.h  : not found

**Comment by original-male** [comment]
Can you provide a backtrace as described [http://non.tuxfamily.org/wiki/BugReports](Here)?

**Comment by layk** [comment]
Two gdb.txt attached:
"Thread 1 "non-mixer" received signal SIGSEGV, Segmentation fault.
0x00007f57c89ee2aa in __strcmp_ssse3 () from /lib64/libc.so.6"

[gdb_1.txt](https://github.com/original-male/non/files/1725200/gdb_1.txt)
[gdb_2.txt](https://github.com/original-male/non/files/1725201/gdb_2.txt)

**Comment by original-male** [comment]
It's hard to tell much from the backtrace, but it looks like the segfault is happening in some library code for which you don't have the debugging symbols installed, probably liblo. Does the "send_osc" program work with non-mixer? Does other software using liblo work for you? Can you install the debugging symbols for liblo and try the backtrace again?

**Comment by layk** [comment]
I did sudo debuginfo-install liblo. It installed following. gdb.txt file attached.
[gdb.txt](https://github.com/original-male/non/files/1725279/gdb.txt)

================================================================================
 Package                         Arch   Version         Repository         Size
================================================================================
Installing:
 glibc-debuginfo                 x86_64 2.26-24.fc27    updates-debuginfo  14 M
 liblo-debuginfo                 x86_64 0.28-6.fc27     fedora-debuginfo   81 k
 yum-plugin-auto-update-debug-info
                                 noarch 1.1.31-513.fc27 fedora             26 k
Installing for dependencies:
 glibc-debuginfo-common          x86_64 2.26-24.fc27    updates-debuginfo  11 M

Transaction Summary
================================================================================
Install  3 Packages (+1 Dependent package)

Total download size: 25 M
Installed size: 159 M
Is this ok [y/d/N]: y
Downloading packages:
(1/4): liblo-debuginfo-0.28-6.fc27.x86_64.rpm               |  81 kB  00:00     
(2/4): yum-plugin-auto-update-debug-info-1.1.31-513.fc27.no |  26 kB  00:01     
(3/4): glibc-debuginfo-common-2.26-24.fc27.x86_64.rpm       |  11 MB  00:02     
(4/4): glibc-debuginfo-2.26-24.fc27.x86_64.rpm              |  14 MB  00:04     
--------------------------------------------------------------------------------

**Comment by layk** [comment]
Using send_osc 4444 /btn7/1 segfaults non-mixer.
Maybe this is a gcc FLAG problem?
gcc --version
gcc (GCC) 7.3.1 20180130 (Red Hat 7.3.1-2)

**Comment by layk** [comment]
And send_osc 4444 /btn/7/1 is received by dump_osc:
dump_osc 4444
listening on URL: osc.udp://localhost:4444/
/btn/7/1 ,

**Comment by layk** [comment]
Fedora 27 seems to use liblo  version 0.28 (on Jan 27, 2014) and the newest is 0.29 (on Aug 11, 2017).
