### ISSUE TITLE
[non-mixer] Learned OSC mappings has no effect

### ISSUE THREAD

**Issue by layk** [original-male/non#228]
Hi
I was able to map OSC messages to controls according to saved project 'mappings' file but those mappings have no effect. The mute button does not toggle and the slider does not move for my test setup project  which was one slider named 'Unnamed'.

Mapping file content:
/seekBar1/39.0 |> /strip/Unnamed/Gain/Gain%20(dB)
/tog8/0 |> /strip/Unnamed/Gain/Mute

Mappings file attached.
[mappings.txt](https://github.com/original-male/non/files/1728724/mappings.txt)

I noticed that in learning mode the slider did not move or the mute button did not toggle but i don't know if that is expected in that mode. 

Tested with fresh git copy today with fix for #227 (Thanks).

**Comment by original-male** [comment]
Do you know/can you configure what kind of datatype your OSC emitter is sending? It needs to be a float (f).

**Comment by layk** [comment]
I 'm using android apps TouchOSC, AndrOSc and  QuickOSC to test so cannot change emitted OSC message.
I collected some data with with dump_osc:
QuickOSC:
/seekBar1/59.0 ,
/seekBar1/60.0 ,
/seekBar1/61.0 ,
/tog8/0 ,
/seekBar1/90.0 ,
/tog8/1 ,
/tog8/0 ,
/seekBar1/89.0 ,
/seekBar1/87.0 ,
/seekBar1/83.0 ,
/seekBar1/78.0 ,
/seekBar1/74.0 ,

AndrOSC:: 
At this point mappings containing:
/vslider |> /strip/Unnamed/Gain/Gain%20(dB)
button |> /strip/Unnamed/Gain/Mute

/tog8/0 ,
/tog8/1 ,
/tog8/0 ,
/tog8/1 ,
button ,i 1
button ,i 1
/vslider ,s 0,827
/vslider ,s 0,827
/vslider ,s 0,823
/vslider ,s 0,817
/vslider ,s 0,803
/vslider ,s 0,783
/vslider ,s 0,766

**Comment by layk** [comment]
This can be closed. My bad. I got this to work with TouchOSC.
Mappings:
/1/fader3 |> /strip/Unnamed/Gain/Gain%20(dB)
/1/toggle3 |> /strip/Unnamed/Gain/Mute

Data:
/1/fader3 ,f 0.5513260364532471
/1/fader3 ,f 0.5526112914085388
/1/toggle3 ,f 0.0
/1/toggle3 ,f 1.0

So it seems that Other clients are sending bad data. TouchOSC seems to get it right.

**Comment by original-male** [comment]
Yeah. Sending apparent float data as a string is especially goofy.
