### ISSUE TITLE
[non-midi-mapper] Core dumped

### ISSUE THREAD

**Issue by layk** [original-male/non#229]
Hi

Just compiled the latest and testing after #227 and running non-midi-mapper i get:
non-midi-mapper 
[non-midi-mapper] OSC URL = osc.udp://localhost:11988/
Segmentation fault (core dumped)

**Comment by original-male** [comment]
Not the most graceful way to deal with it, but non-midi-mapper only works in an NSM session and this is how it dies when run outside of one. Where you trying to use it outside of NSM?

**Comment by layk** [comment]
Yes i was runnig outside NSM. I will invstigate.

**Comment by layk** [comment]
I can use non-midi-mapper inside NSM session. Closing.
