### ISSUE TITLE
[non-session-manager] Preview session before opening it.

### ISSUE THREAD

**Issue by diovudau** [original-male/non#236]
This is an important request for me:
Please change NSM GUI behaviour to first preview the session members before actually starting it.
There are multiple options ways to implement this, like click vs double click or using the right mouse button for a preview (to not break current expectations)

**Comment by grammoboy2** [comment]
For me as a user, I don't see why I would need this atm. Also, wouldn't it make the gui unnecessary complicated? 

Couldn't this be solved by giving the session a recognizable name? Organize sessions in different subfolders? Do a 'cat  session.nsm'? 

Open the session and then abort as last option.

**Comment by original-male** [comment]
Yeah, I need more context to understand how this would be helpful. For me, most of my sessions have the same clients, so seeing a list of the clients in a session wouldn't really tell me anything. Maybe you're looking for something like non-timeline's project notes feature, but at a session level?
