### ISSUE TITLE
[non-session-manager] Add Client to Session: Tab completition, better error visibility and menus

### ISSUE THREAD

**Issue by diovudau** [original-male/non#237]
I think for a regular user to type in the name of the program is too much to ask for and massively hurts adoption for NSM. Especially since many programs choose to create different executable files, maybe exactly to satisfy NSMs strict command line switch rules. 

So please add one or both of these options:

Tab completition / suggestions for the current starter dialog.  synthv1-jack and carla_jack_multi are not easy to remember and even easier to misspell. Especially since even this example is wrong and - and _ should be switched.

In the same vain NSM could refuse to add a program that returns with "No such file or directory", a state you are already aware of. From the GUI perspective a non-existent program looks the same as a crashing one. This information is not included in NSM log window, which you would need to find first  This behaviour trains NSM users to always start its gui through a terminal to find out what went wrong. We live in a linux audio world where programs crash often and do not start for various reasons. The reasons should be included in the log. 

A real benefit for normal users would be to create a real menu and possibly other convenience options like drag&drop desktop files or menu entries (e.g. XFCE menu) into the NSM window.

**Comment by grammoboy2** [comment]
FYI: I think it's this section male is talking about:

" When nsmd starts, it will print a string of the following form its standard output.

NSM_URL=osc.udp://foo.bar.net:17551/

This is the OSC URL for the daemon process. If this URL is included in the environment (by either using a fixed port number or starting nsmd early in the initialization process [like in your .xinitrc] extracting the URL from its output) then any NSM capable client will join the current session when started, even if started from outside the Non Session Manager interface (for example, by your Desktop Environment's program launch menu). "
http://non.tuxfamily.org/session-manager/doc/MANUAL.html

**Comment by grammoboy2** [comment]
I'm not sure how this is actually working. You can start nsmd with a fixed osc port:
 
nsmd --osc-port 15000

And then start non-session-manager: 

 non-session-manager --nsm-url osc.udp://foo.bar.net:15000/

But that isn't enough to get this 'feature' working apparently.

**Comment by original-male** [comment]
Clients will not know how to contact NSM unless you add NSM_URL to the environment of the process that launches them (and they inherit it).

**Comment by grammoboy2** [comment]
using Ubuntu, LXDE-openbox. in my .xinitrc:
NSM_URL=osc.udp://foo.bar.net:15000/

Then in terminal:

nsmd --osc-port 15000

Then in terminal:

non-session-manager --nsm-url osc.udp://foo.bar.net:15000/

Then i need to make a new session from the gui, then launching zynaddsubfx should join that session? Doesn't work here. Maybe you can give a example, that works best most of the time.

**Comment by royvegard** [comment]
Something like this in .xinitrc:
```
nsmd --osc-port 17882 &
export NSM_URL=osc.udp://ub-mix:17882/
```
My hostname is ub-mix, you'll have to use your hostname.
This should start nsmd and set the NSM_URL environment.

You have to at least restart your X session. Now you can start non-session-manager (you don't need to give it the nsm-url, it will find the already running nsmd). Start or open a session. Now you can add clients to that session by starting them by any means.

**Comment by grammoboy2** [comment]
On 20-02-2020 21:13, Roy Vegard Ovesen wrote:
>
> Something like this in .xinitrc:
>
> |nsmd --osc-port 17882 & export NSM_URL=osc.udp://ub-mix:17882/ |
>
> My hostname is ub-mix, you'll have to use your hostname.
> This should start nsmd and set the NSM_URL environment.
>
> You have to at least restart your X session. Now you can start
> non-session-manager (you don't need to give it the nsm-url, it will
> find the already running nsmd). Start or open a session. Now you can
> add clients to that session by starting them by any means.
>
Thanks. Will test it in the coming days.
>

**Comment by grammoboy2** [comment]
On 2/20/20 9:13 PM, Roy Vegard Ovesen wrote:
>
> Something like this in .xinitrc:
>
> |nsmd --osc-port 17882 & export NSM_URL=osc.udp://ub-mix:17882/ |
>
> My hostname is ub-mix, you'll have to use your hostname.
> This should start nsmd and set the NSM_URL environment.
>
> You have to at least restart your X session. Now you can start 
> non-session-manager (you don't need to give it the nsm-url, it will 
> find the already running nsmd). Start or open a session. Now you can 
> add clients to that session by starting them by any means.
>
Thanks, but doesn't work here. Non-session-manager doesn't use the osc 
port set in .xinitrc.
>
