### ISSUE TITLE
[non-session-manager] Start programs in their last GUI state

### ISSUE THREAD

**Issue by diovudau** [original-male/non#238]
Currently all optional GUI programs start with their GUI open. NSM should save their state and send them a message after load.

For programs that simply supply audio output, synths and samplers, the view gets really messy after startup. I use NSM to not use a plugin host (or rather my operating system and NSM is my "plugin host") and having multiple programs such as drumkv_1 or zynaddsubfx, in multiple instances, creates a window explosion on session start.

**Comment by grammoboy2** [comment]
I'm using 4-6 different workspaces on my Desktop. I found the default Gnome3 Desktop not very good for audio. Using LXDE on top of it now. Did have good experience with fluxbox/openbox too.

**Comment by diovudau** [comment]
When I created this ticket years ago I was mistaken.
It is the responsibility of the program to save its state, not the session managers.
