### ISSUE TITLE
[non-session-manager] Option to rename clients in the GUI (pretty name)

### ISSUE THREAD

**Issue by diovudau** [original-male/non#239]
Multiple instances of the same program are indistinguishable in the NSM GUi. Please add the option to give them aliases.

**Comment by grammoboy2** [comment]
i agree that this could make it more pleasant to work with nsm GUI.

**Comment by diovudau** [comment]
NSM supports Client->Server `/nsm/client/label` which is a pretty name
and will report that correctly to the attached NSM Gui with `/nsm/gui/client/label`

However, this is not saved in `session.nsm` so each client would have to provide and remember its label and send it on every startup. Which is a different workflow than envisioned because it needs client support and thus will not work with dumb clients.
