### ISSUE TITLE
Using nsm-proxy to launch a2j midi bridge

### ISSUE THREAD

**Issue by miquecg** [original-male/non#247]
I'm using Non Session Manager with Carla and JACKPatch and so far it's been great. Now I'd like to improve my workflow just a little by adding a2j MIDI bridge to the session setup.

As far as I can tell, Carla doesn't remember to restart the bridge so I have to do it myself every time. To avoid it I've added a `nsm-proxy` client to the session that calls `a2j_control` command. It works, the bridge is started and I can see MIDI hardware ports in the patchbay.

The only issue is that `nsm-proxy` client dies unexpectedly right after starting but it doesn't seem like a real problem. I've passed two different arguments to the command:

> start
> start > /dev/null

Is what I'm trying to do possible or there are better options for saving a2j bridge status in the session?

**Comment by original-male** [comment]
I haven't used a2j since jackd got the -x seq option (which allows the
whole graph to be managed by JACKPatch... So you'll have to refresh my
memory on how the command works and how your NSM Proxy instance is
configured with it. NSM Proxy will terminate when the proxied client
terminates... Do you have any console output?

**Comment by miquecg** [comment]
I'm using `jack2-dbus` and Cadence for server settings.

How to reproduce the issue:
1. Start Non Session Manager and create a new session
2. Add client `nsm-proxy`
3. In the GUI for configuring the client set
    - Executable: `a2j_control`
    - Arguments: `start`
    - Save Signal: `None` (default)
    - Stop Signal: `SIGTERM` (default)
4. Bridge successfully started but client NSM Proxy status is stopped and in the bottom bar there's this message: `Client NSM Proxy died unexpectedly.`

JACK log:
> Mon Feb 18 12:58:11 2019: New client 'a2j' with PID 3426

A2J log:
> Mon Feb 18 12:58:11 2019: Bridge starting...
> Mon Feb 18 12:58:11 2019: Using JACK server 'default'
> Mon Feb 18 12:58:11 2019: Hardware ports will be exported.
> Mon Feb 18 12:58:11 2019: Bridge started
> Mon Feb 18 12:58:11 2019: port created: Midi Through [14] (capture): Midi Through Port-0
> Mon Feb 18 12:58:11 2019: port created: Midi Through [14] (playback): Midi Through Port-0

> NSM Proxy will terminate when the proxied client terminates...

Makes total sense and it's what's happening here. `a2j_control start` is a one-shot command, not a real client for the session. In this case looks more like a cosmetic issue than a real problem.

Are there any other options for executing this kind of post-start commands?

**Comment by original-male** [comment]
> Are there any other options for executing this kind of post-start commands?

Not currently. There has been some talk of adding session hook type things, but just about every time it comes up it seems superfluous on further thought.

One thing you could do is create a shell script to wrap your a2j_control that just executes the command and then sleeps forever and use the script as the executable in NSM Proxy. That way NSM Proxy wouldn't terminate. Ideally you'd also want this script to respond to SIGUSR1 by running whatever command is required to save whatever dynamic a2j state isn't expressed in the JACK graph.

**Comment by original-male** [comment]
(in fact, if one wanted to be clever, one could have this script be generic, called session-start-hook or something, and have it pull its config/commands from within the session directory, thereby creating the desired hook functionality. However, stuff like this breaks the portability of sessions, such a script as session-start-hook very specific to the environment present on one machine.)

**Comment by miquecg** [comment]
Thanks for your suggestions. It turns out that it's possible to call `a2jmidid` instead [1] and this prevents the `nsm-proxy` client from terminating because it's a daemon.

[1] https://github.com/falkTX/Carla/issues/843
