### ISSUE TITLE
Could not find the program ['pkg-config']

### ISSUE THREAD

**Issue by pteeson** [original-male/non#250]
I am assuming it's feasible to build on macOS. But it I'm wrong please correct me.My gear is
macOS 10.12.6 Sierra on a Mac Pro. 
In following README.build it fails on step "Building NTK" command ./waf configure. 
Processor lacks sse, disabling...
Checking for program 'pkg-config'                    : not found 
Could not find the program ['pkg-config']
(complete log in /Volumes/Data/Development/Raspberrypi/non/build/config.log)

Searched for it this way:
Gandalf:non pteeson$ which pkg_config
Gandalf:non pteeson$ locate pkg-config
/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/numpy/core/lib/npy-pkg-config
/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/numpy/core/lib/npy-pkg-config/mlib.ini
/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/numpy/core/lib/npy-pkg-config/npymath.ini

Any suggestions?   TIA

P.S. I have an RPI 3B+ I want to try a little project using Non *

**Comment by original-male** [comment]
Porting to MacOS is definitely an exercise for the reader. Not an easy task.

**Comment by rhetr** [comment]
If you're just trying to compile for the RPi you could just compile non on the RPI itself. Or set up a linux VM on macos to cross-compile.

**Comment by pteeson** [comment]
Yes thanks for the suggestion... I have had a VBox vm for Raspbian for a couple of years So I'll play with that.
