### ISSUE TITLE
Please do not use signalfd(2) because it is a problematic API

### ISSUE THREAD

**Issue by yurivict** [original-male/non#252]
signalfd(2) can't possibly work reliably because file API can itself terminate with signals that the application receives when it reads signals.

Could you please replace it with a regular signal processing?

On FreeBSD we have ~32,000 ports and not a single other port uses signalfd(2) for this reason. It isn't available on BSDs for the same reason.

Thank you,
Yuri

**Comment by original-male** [comment]
I'd accept a pull reuqest for this if it didn't change any performance or behavior characteristics or if it was #ifdef'd only to apply to FreeBSD.
