### ISSUE TITLE
sources for ntk_fluid.py missing

### ISSUE THREAD

**Issue by dvzrv** [original-male/non#253]
Hi!
I'm currently rebuilding a bunch of projects with a system installation of waf and am also trying to do this for non.
However, the included file ntk_fluid.py as loaded in wscript (https://github.com/original-male/non/blob/master/wscript#L34) is not available anywhere.

Please add it to this repository, as it is more than awkward not having the sources for the binary blob build system available to build a GPLv2 licensed software.

It is otherwise impossible to reproduce builds in the future, if the current version of waf introduces incompatibilities towards python3 and it is currently impossible to use system installations of waf because of this.

**Comment by dvzrv** [comment]
It is possible to use waf with a local waflib directory (it will be used by a local waf) and adding the custom script to e.g. `waflib/extras/`.
This would look like:

```
waf
wscript
waflib/
- Tools/
  - [..]
- extras/
  - [..]
  - ntk_fluid.py
```

Otherwise, it is possible to use the `load` function with the `tooldir` parameter. This would probably allow for a pretty vanilla install of waf (with only some default modules built in).
In the wscript, use e.g. `conf.load('ntk_fluid', tooldir='tools')` and then have a standard installation of waf in your repository and the `ntk_fluid.py` file in a `tools` directory:

```
waf
wscript
tools/
- ntk_fluid.py
```

I guess both options give better visibility over the current setup, although the first is a little more convoluted.

**Comment by original-male** [comment]
The first option fails because it expects all of waflib to exist at that location, not just the module in question.

The second option fails because apparently it just doesn't work (the tooldir argument appears to be ignored).

So I'm left once again not knowing of a better way to do this than build it into waf (which I never liked having to do in the first place).

**Comment by original-male** [comment]
(upgrading to a newer waf version made option #2 work)

**Comment by dvzrv** [comment]
On 2019-09-25 00:13:16 (-0700), Jonathan Moore Liles wrote:
> (upgrading to a newer waf version made option #2 work)

Can you please at least add the missing file to the repository, so it
can be used separately? :)

-- 
https://sleepmap.de

**Comment by original-male** [comment]
I did. It's in tools.waf/ntk_fluid.py and referenced in the wscript using the tooldir argument to conf.load(). That trick didn't work with waf 2.0.9, but it did with 2.0.18.

**Comment by dvzrv** [comment]
On 2019-09-25 00:38:35 (-0700), Jonathan Moore Liles wrote:
> I did. It's in tools.waf/ntk_fluid.py and referenced in the wscript
> using the tooldir argument to conf.load(). That trick didn't work with
> waf 2.0.9, but it did with 2.0.18.

Oh neat! I misread your reply. Thank you!! :)

-- 
https://sleepmap.de
