### ISSUE TITLE
[NSM] Make a crossplatform GUI

### ISSUE THREAD

**Issue by grammoboy2** [original-male/non#272]
All though the fact that NSM is probably most beneficial on Linux, it could proof to be useful on Windows and OSX as well. 

Ardour and Carla are cross platform and have NSM support for instance. 

It would be good to have a NSM GUI that works on Windows and OSX too. Whether that is priority, or whether it should be the default GUI, is a open question.

**Comment by falkTX** [comment]
I dont see how NSM can work on Windows, taken you have to pass the full filename to the executable in order to find them.

**Comment by grammoboy2** [comment]
Ok, for Windows jack-session is a option then maybe for a plugin host like Carla if you want to use it with Ardour for example.
