### ISSUE TITLE
[NSM] feature request: remove a session from the list in the GUI

### ISSUE THREAD

**Issue by grammoboy2** [original-male/non#273]
As discussed via e-mail:

Add the possibility to remove a session from the GUI. Now each experiment or testing a new application using the Non-Session-Manager adds a new session to the list, which can get pretty messy soon. If you could remove this session from the GUI easily, I think i find myself reaching for Non-Session-Manager more easy at start of such a 'experimental' session.

Removing it from the list, without actually removing the session from hdd would be a interesting option

**Comment by nico202** [comment]
Can this implemented simply by touching a file in the session?

touch sessions/session-name/.disabled

and skipping sessions with this file inside?  Manual intervention should be required to re-enable them (deleting the file)

**Comment by grammoboy2** [comment]
Some background discussion for reference:

"The ability to remove sessions is frightening. I don't like the idea of accidentally, irreversibly deleting something that represents such a huge time investment from the user. IMHO, it *should* be difficult to delete a project.
The simplest thing would just to be to rename the file "session.nsm" to '#session.nsm' or something similar, which would keep it from appearing in the sessions list. If the user really wanted to from it from the f/s they could rm -rf the directory, and if they wanted to restore it, they could rename the file back to what it should be called (no way to do this from the GUI since it doesn't show up there anymore).

Probably a right click on the session name in the list bringing up a context menu with a "remove" option."
