### ISSUE TITLE
[NSM] Can't restore connections, for any client.

### ISSUE THREAD

**Issue by moonshaadow** [original-male/non#278]
Hi there.
I'm using NSM from @falkTX repositories on ubuntu studio 18.04.

None connections are saved when I close a session
Nothing relevant in the log.

**Comment by nico202** [comment]
If I remember well, by default, nsm does not store connections.  Did you add `jackpatch` to the session?

**Comment by moonshaadow** [comment]
Ok, thank's. I haden't tried with `jackpatch`, I didn't even known about it, assuming that a session manager should restore automatically jack connections... 
It's working well with `jackpatch`, thank's for the quick answer!
