### ISSUE TITLE
(Non-Timeline) Feature Request: Using FLAC file format on timeline's tracks

### ISSUE THREAD

**Issue by aliteral** [original-male/non#283]
Hi male, Im a musician from South America. I learned about the open source/free software community months ago, and I fell in love with it. I settled up to using Non over Ardour, as I like the concept of modularity and reliability the project has achieved. I have however, this concern. I don't find possible to use .flac audio files instead of .wav. 
Being .flac the free alternative to .wav, shouldn't we use it in our projects? If I am wrong over something I said, feel free to correct me, as I am still learning about all this. Is it possible to use this type of files on the timeline, and if not, could it be a new feature?
Thank you for your time and effort!

**Comment by grammoboy2** [comment]
> Hi male, Im a musician from South America. I learned about the open 
> source/free software community months ago, and I fell in love with it. 
> I settled up to using Non over Ardour, as I like the concept of 
> modularity and reliability the project has achieved. I have however, 
> this concern. I don't find possible to use .flac audio files instead 
> of .wav.
> Being .flac the free alternative to .wav, shouldn't we use it in our 
> projects? If I am wrong over something I said, feel free to correct 
> me, as I am still learning about all this. Is it possible to use this 
> type of files on the timeline, and if not, could it be a new feature?
> Thank you for your time and effort!
>
Flac should just work afaik.
>

**Comment by aliteral** [comment]
It throws and error message saying:
Could not import the file when I drag and drop from my file manager.
When I try to use the "import source at cursor" option, it does the same thing.

**Comment by grammoboy2** [comment]
On 5/2/20 10:12 PM, aliteral wrote:
>
> It throws and error message saying:
> Could not import the file when I drag and drop from my file manager.
> When I try to use the "import source at cursor" option, it does the 
> same thing.
>
Did you test other files? Here tested a quick flac file, and it works.
>

**Comment by aliteral** [comment]
I have tested it before. I will do it again nonetheless. Thank you!.
