### ISSUE TITLE
What is the license of NSM_Proxy_UI.fl ?

### ISSUE THREAD

**Issue by diovudau** [original-male/non#288]
For very strict packaging and distributions only the header in a file or something comparably explicit counts as licensing.
`session-manager/NSM_Proxy_UI.fl`, as a file created by the FLTK gui tool, has no license header. 
It is natural to assume that this file is GPL, like the rest of the project, but better safe than sorry.

Given the very stable nature of this file (no edit in years) could a license header please be added as comment at the top?

**Comment by original-male** [comment]
The license is learn to write your own code.
