### ISSUE TITLE
[nsm] jackpatch fails to start sometimes with duplicate

### ISSUE THREAD

**Issue by grammoboy2** [original-male/non#49]
jackpatch fails to start sometimes with the duplicate function. Also I did have to restart jackpatch in a duplicated session, to restore the connections between non-mixer and soundcard playback

**Comment by schrotie** [comment]
I might be seeing the same problem - a duplicate session does not reproduce the connection graph. I think I see this every time ... on a dedicated audio machine in the rehearsal room to which I do not always have access. Can I do anything to help get this analysed?

**Comment by grammoboy2** [comment]
I didn't experience this lately.
